export const demoPages = [
  { id: 1, title: 'Home', path: '/demo/1' },
  { id: 2, title: 'Login', path: '/demo/2' },
  { id: 3, title: 'Coaches Signup', path: '/demo/3' },
  { id: 4, title: 'Clients Signup', path: '/demo/4' },
  { id: 5, title: 'Coaches Dashboard', path: '/demo/5' },
  { id: 6, title: 'Coach Profile', path: '/demo/6' },
  { id: 7, title: 'Schedule', path: '/demo/7' },
  { id: 8, title: 'Sessions', path: '/demo/8' },
  { id: 9, title: 'Post Session Report', path: '/demo/9' },
  { id: 10, title: 'Coached Client List', path: '/demo/10' },
  { id: 11, title: 'Client Progress', path: '/demo/11' },
  { id: 12, title: 'Availability Settings', path: '/demo/12' },
  { id: 13, title: 'Pricing Settings', path: '/demo/13' },
  { id: 14, title: 'Client Dashboard', path: '/demo/14' },
  { id: 15, title: 'Booking Session', path: '/demo/15' },
  { id: 16, title: 'My Sessions', path: '/demo/16' },
  { id: 17, title: 'Progress Dashboard', path: '/demo/17' },
  { id: 18, title: 'Progress History', path: '/demo/18' },
  { id: 19, title: 'Weather Alerts/Cancel Session', path: '/demo/19' },
  { id: 20, title: 'Messages (Coaches View)', path: '/demo/20' },
  { id: 21, title: 'Messages (Clients View)', path: '/demo/21' },
];
